apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-keda
  namespace: NAMESPACE_PLACEHOLDER
spec:
  addonRef:
    name: keda
    namespace: vmware-system-vks-public
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: CLUSTER_NAME_PLACEHOLDER
  crossNamespaceSelection: Blocked
  stopMatchingBehavior: Delete
